config/urls.py
from django.contrib import admin
from django.urls import conf, path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('itsuki/', include('itsuki.urls')),
    path('accounts/', include('allauth.urls')),
]

from django.contrib.staticfiles.urls import static
from . import settings
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kuroiwa/urls.py
from django.urls import path
from . import views

app_name = 'kuroiwa'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('diary_list/',views.DiaryListView.as_view(),name = 'diary_list'),
    path('diary-detail/<int:pk>/',views.DiaryDetailView.as_view(),name="diary_detail"),
    path('diary-create/', views.DiaryCreateView.as_view(),name="diary_create"),
    path('diary-update/<int:pk>/',views.DiaryUpdateView.as_view(),name="diary_update"),
    path('diary-delete/<int:pk>/', views.DiaryDeleteView.as_view(),name="diary_delete"),
]

riku/urls.py
from django.urls import path
from . import views

app_name = 'Riku'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('inquiry/',views.InquiryView.as_view(),name="inquiry"),
    path('diary_list/',views.DiaryListView.as_view(),name="diary_list"),
    path('diary_detail/<int:pk>/',views.DiaryDetailView.as_view(),name="diary_detail"),
    path('diary_create/',views.DiaryCreateView.as_view(),name="diary_create"),
    path('diary_update/<int:pk>/',views.DiaryUpdateView.as_view(),name="diary_update"),
    path('diary_delete/<int:pk>/',views.DiaryDeleteView.as_view(),name="diary_delete"),


]

kuroiwa/models.py
from accounts.models import CustomUser
from django.db import models

# Create your models here.

class Diary(models.Model):
    """日記モデル"""

    user = models.ForeignKey(CustomUser, verbose_name='ユーザ', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    content = models.TextField(verbose_name='本文', blank=True,null=True)
    photo1 = models.ImageField(verbose_name='写真1', blank = True,null = True)
    photo2 = models.ImageField(verbose_name='写真2', blank = True,null = True)
    photo3 = models.ImageField(verbose_name='写真3', blank = True,null = True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時',auto_now=True)

    class Meta:
        verbose_name_plural = 'Diary'

    def __str__(self):
        return self.title

kuroiwa/forms.py
from django import forms
from django.core.mail import EmailMessage

class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前',max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル',max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)


    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'
        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'
        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'
        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = 'admin@example.com'
        to_list = [
            'test@example.com'
        ]
        cc_list = [
            email
        ]

        msg= EmailMessage(subject=subject,body=message,from_email=from_email,to=to_list,cc=cc_list)
        msg.send()

from .models import Diary

class DiaryCreateForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('title', 'content', 'photo1', 'photo2', 'photo3',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

kuroiwa/views.py
#from django.http.response import HttpResponse
#import logging
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views import generic
from.forms import InquiryForm
from django.contrib import messages

#logger = logging.getLogger(__name__)

# Create your views here.
def index(request):
    return render(request, 'index.html')

class IndexView(generic.TemplateView):
    template_name = "index.html"

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('kuroiwa:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request,'メッセージを送信しました。')
        #logger.info('Inquiry send by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)

from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Diary

class DiaryListView(LoginRequiredMixin, generic.ListView):
    model = Diary
    template_name = 'diary_list.html'
    paginate_by = 2

    def get_queryset(self):
        diaries = Diary.objects.filter(user=self.request.user).order_by('-created_at')
        return diaries

class DiaryDetailView(LoginRequiredMixin, generic.DetailView):
    model = Diary
    template_name = 'diary_detail.html'
    #pk_url_kwarg = 'id'


from.forms import InquiryForm, DiaryCreateForm

class DiaryCreateView(LoginRequiredMixin, generic.CreateView):
    model = Diary
    template_name = 'diary_create.html'
    form_class = DiaryCreateForm
    success_url = reverse_lazy('kuroiwa:diary_list')

    def form_valid(self, form):
        diary = form.save(commit=False)
        diary.user = self.request.user
        diary.save()
        messages.success(self.request, '日記を作成しました。')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, "日記の作成に失敗しました。")
        return super().form_invalid(form)


class DiaryUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Diary
    template_name = 'diary_update.html'
    form_class = DiaryCreateForm

    def get_success_url(self):
        return reverse_lazy('kuroiwa:diary_detail', kwargs={'pk':self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, '日記を更新しました。')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, "日記の更新に失敗しました。")
        return super().form_invalid(form)


class DiaryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Diary
    template_name = 'diary_delete.html'
    success_url = reverse_lazy('kuroiwa:diary_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "日記を削除しました。")
        return super().delete(request, *args, **kwargs)

kuroiwa/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
        type="text/css" />
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
        rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'css/mystyles.css' %}" rel="stylesheet" />
    {% block head %}{% endblock %}
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'kuroiwa:index' %}">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4"
                            href="{% url 'kuroiwa:inquiry' %}">Inquiry</a></li>
                    {% if user.is_authenticated %}
                    <li class="nav-item {% block active_diary_list %}{% endblock %}"></li>
                    <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'kuroiwa:diary_list' %}">DIARY LIST</a>
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'account_logout' %}">Log
                            out</a></li>
                    {% else %}
                    <li class="nav-item {% block active_signup %}{% endblock %}"><a
                            class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'account_signup' %}">Sign Up</a></li>
                    <li class="nav-item {% block active_login %}{% endblock %}"><a class="nav-link px-lg-3 py-3 py-lg-4"
                            href="{% url 'account_login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Header-->
    {% block header %}{% endblock %}

    {% if messages %}
    <div class="container">
        <div class="row">
            <div class="my-div-style w-100">
                <ul class="messages" style="list-style: none;">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                        {{ message }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- contents -->
    {% block contents %}{% endblock %}
    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

kuroiwa/templates/diary_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}日記作成 | PrivateDiary{% endblock %}
{% block header%}
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>DIARY CREATE</h1>
                    <span class="subheading">日記の新規作成</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block active_diary_list %}active{% endblock %}
{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

kuroiwa/templates/diary_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}日記削除 | PrivateDiary{% endblock %}
{% block header%}
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>DIARY DELETE</h1>
                    <span class="subheading">日記の削除</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block active_diary_list %}active{% endblock %}
{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST">
                {% csrf_token %}
                <p>本当に削除しますか？</p>
                <button class="btn btn-primary mt-5" type="submit">削除</button>
                <a class="btn btn-secondary mt-5 ml-2" href="{% url 'kuroiwa:diary_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

kuroiwa/templates/diary_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記詳細 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <div class="row">
            <div class="col-3">
                <strong>タイトル</strong>
            </div>
            <div class="col-9">
                {{ object.title }}
            </div>
        </div>
        <hr>

        <div class="row">
            <div class="col-3">
                <strong>本文</strong>
            </div>
            <div class="col-9">
                {{ object.contact|linebreaksbr}}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>写真</strong>
            </div>
            <div class="col-3">
                {% if object.photo1 %}
                <img src="{{ object.photo1.url }}" width="200" height="200" />
                {% endif %}
            </div>
            <div class="col3">
                {% if object.photo2 %}
                <img src="{{ object.photo2.url }}" width="200" height="200" />
                {% endif %}
            </div>
            <div class="col3">
                {% if object.photo3 %}
                <img src="{{ object.photo3.url }}" width="200" height="200" />
                {% endif %}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>作成日時</strong>
            </div>
            <div class="col-9">
                {{ object.create_at}}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>更新日時</strong>>
            </div>
            <div class="col-9">
                {{ object.updated_at}}
            </div>
        </div>
        <a class="btn btn-success mt-5 mb-3" href="{% url 'kuroiwa:diary_update' object.pk %}">編集</a>
        <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'kuroiwa:diary_delete' object.pk %">削除</a>
    </div>
</div>
{%endblock%}

kuroiwa/templates/diary_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}日記一覧 | PrivateDiary{% endblock %}
{% block header%}
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>DIARY LIST</h1>
                    <span class="subheading">日記の一覧</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="clearfix">
                    <a class="btn btn-primary float-right" href="{% url 'kuroiwa:diary_create' %}">新規作成</a>
                </div>
                {% for diary in diary_list %}
                <div class="post-preview">
                    <a href="{% url 'kuroiwa:diary_detail' diary.pk %}">
                        <h2 class="post-title">
                            {{ diary.title}}
                        </h2>
                        <h3 class="post-subtitle">
                            {{ diary.content|truncatechars:20 }}
                        </h3>
                    </a>
                    <p class="post-meta">{{ diary.created_at }}</p>
                </div>
                <hr>
                {% empty %}
                <p>日記がありません。</p>
                {% endfor %}

                {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page_item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif %}
                    {% for page_num in page_obj.paginator.page_range %}
                    {% if page_obj.number == page_num %}
                    <li class="page-item active">
                        <a class="page-link" href="#">{{ page_num }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

kuroiwa/templates/diary_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}日記編集 | PrivateDiary{% endblock %}
{% block header%}
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Diary Update</h1>
                    <span class="subheading">日記の編集</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block active_diary_list %}active{% endblock %}
{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">更新</button>
                <a class="btn btn-secondary ml-2" href="{% url 'kuroiwa:diary_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

kuroiwa/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Web上にあなた専用の日記ページを保存できるサービス | Private Diary{% endblock %}
{% block header%}
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Private Diary</h1>
                    <span class="subheading">あなた専用の日記保存サービス</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block contents %}
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            <div class="post-preview">
                <a href="post.html">
                    <h2 class="post-title">Man must explore, and this is exploration at its greatest</h2>
                    <h3 class="post-subtitle">Problems look mighty small from 150 miles up</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Start Bootstrap</a>
                    on September 24, 2021
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Post preview-->
            <div class="post-preview">
                <a href="post.html">
                    <h2 class="post-title">I believe every human has a finite number of heartbeats. I don't intend to
                        waste any of mine.</h2>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Start Bootstrap</a>
                    on September 18, 2021
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Post preview-->
            <div class="post-preview">
                <a href="post.html">
                    <h2 class="post-title">Science has not yet mastered prophecy</h2>
                    <h3 class="post-subtitle">We predict too much for the next year and yet far too little for the next
                        ten.</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Start Bootstrap</a>
                    on August 24, 2021
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Post preview-->
            <div class="post-preview">
                <a href="post.html">
                    <h2 class="post-title">Failure is not an option</h2>
                    <h3 class="post-subtitle">Many say exploration is part of our destiny, but it’s actually our duty to
                        future generations.</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Start Bootstrap</a>
                    on July 8, 2021
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Pager-->
            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts
                    →</a></div>
        </div>
    </div>
</div>
{% endblock %}

kuroiwa/templates/inquiry.html
{% extends 'base.html' %}
{% load static %}
{% block title %}お問い合わせ | Private Diary{% endblock %}
{% block header%}
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>INQUIRY</h1>
                    <span class="subheading">お問い合わせ</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block active_inquiry %}active{% endblock%}
{% block contents %}
<!-- Content section 1-->
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="POST">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form%}
                <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                        <strong>{{ field.label_tag }}</strong>
                    </label>
                    <div class="col-sm-8">
                        {{ field }}
                        {{ field.errors}}
                    </div>
                </div>
                {% endfor %}
                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock %}